### ISSUE TITLE
NETStandard version of SecureStorage?

### ISSUE THREAD

**Issue by dfarrNTST** [sameerkapps/SecureStorage#26]
Is there a NETStandard version of this package available or on the roadmap?  We are moving all of our library development to .NETStandard 2.0.

**Comment by sameerkapps** [comment]
It is on the roadmap.

**Comment by dfarrNTST** [comment]
Thanks...a rough estimate of when it might be available?

**Comment by sameerkapps** [comment]
Will do it in the holiday season.

**Comment by sameerkapps** [comment]
Done! Please check the source and the latest NuGet package.

**Comment by rintje** [comment]
Hi, despite upgrading to SecureStorage 2.0 i am still getting a netstandard related compiler warning:

`warning NU1701: Package 'sameerIOTApps.Plugin.SecureStorage 2.0.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.`

Tried to uninstall / install the nuget, but the warning won't go away. It seems to work fine though.
My host project is a Xamarin.forms .netstandard 2.0 library in a Xamarin.Forms solution.
